---
driver:
  name: vagrant

verifier:
  name: inspec

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-16.10

suites:
  - name: default
    run_list:
      - recipe[qgis::default]
